
use aspnet_EmpressOfLight
go


insert into [Categories] values
	('Jacket'),
	('Sweater'),
	('Men T-Shirt'),
	('Men Jeans'),
	('Women Jeans'),
	('Women Croptop')
go


insert into [Products] values
	(1, 'White Slyteam Jacket', 'https://i.etsystatic.com/46614834/r/il/d359de/5292147314/il_600x600.5292147314_6s0i.jpg', 'Nulla eget sem vitae eros pharetra viverra. Mauris consequat ornare feugiat', 'Aenean sit amet gravida nisi. Nam fermentum est felis, quis feugiat nunc fringilla sit amet. Ut in blandit ipsum. Quisque luctus dui at ante aliquet, in hendrerit lectus interdum. Morbi elementum sapien rhoncus pretium maximus. Nulla lectus enim, cursus et elementum sed, sodales vitae eros. Ut ex quam, porta consequat interdum in, faucibus eu velit. Quisque rhoncus ex ac libero varius molestie. Aenean tempor sit amet orci nec iaculis. Cras sit amet nulla libero. Curabitur dignissim, nunc nec laoreet consequat, purus nunc porta lacus, vel efficitur tellus augue in ipsum. Cras in arcu sed metus rutrum iaculis. Nulla non tempor erat. Duis in egestas nunc.\r\n', 50, 220000),
	(1, 'Black Slyteam Jacket', 'https://i.etsystatic.com/36203218/r/il/c56494/4146214008/il_600x600.4146214008_oue6.jpg', 'Nulla eget sem vitae eros pharetra viverra. Mauris consequat ornare feugiat', 'Aenean sit amet gravida nisi. Nam fermentum est felis, quis feugiat nunc fringilla sit amet. Ut in blandit ipsum. Quisque luctus dui at ante aliquet, in hendrerit lectus interdum. Morbi elementum sapien rhoncus pretium maximus. Nulla lectus enim, cursus et elementum sed, sodales vitae eros. Ut ex quam, porta consequat interdum in, faucibus eu velit. Quisque rhoncus ex ac libero varius molestie. Aenean tempor sit amet orci nec iaculis. Cras sit amet nulla libero. Curabitur dignissim, nunc nec laoreet consequat, purus nunc porta lacus, vel efficitur tellus augue in ipsum. Cras in arcu sed metus rutrum iaculis. Nulla non tempor erat. Duis in egestas nunc.\r\n', 90, 300000),
	(1, 'Doncare Prom Jacket', 'https://i.etsystatic.com/45814775/c/2000/2000/0/0/il/8f21a6/5302991298/il_600x600.5302991298_m9zk.jpg', 'Nulla eget sem vitae eros pharetra viverra. Mauris consequat ornare feugiat', 'Aenean sit amet gravida nisi. Nam fermentum est felis, quis feugiat nunc fringilla sit amet. Ut in blandit ipsum. Quisque luctus dui at ante aliquet, in hendrerit lectus interdum. Morbi elementum sapien rhoncus pretium maximus. Nulla lectus enim, cursus et elementum sed, sodales vitae eros. Ut ex quam, porta consequat interdum in, faucibus eu velit. Quisque rhoncus ex ac libero varius molestie. Aenean tempor sit amet orci nec iaculis. Cras sit amet nulla libero. Curabitur dignissim, nunc nec laoreet consequat, purus nunc porta lacus, vel efficitur tellus augue in ipsum. Cras in arcu sed metus rutrum iaculis. Nulla non tempor erat. Duis in egestas nunc.\r\n', 30, 450000),
	
	(2, 'Sweater Champion White', 'https://i.etsystatic.com/37453946/r/il/e09f56/4188521719/il_600x600.4188521719_9utq.jpg', 'Nulla eget sem vitae eros pharetra viverra. Mauris consequat ornare feugiat', 'Aenean sit amet gravida nisi. Nam fermentum est felis, quis feugiat nunc fringilla sit amet. Ut in blandit ipsum. Quisque luctus dui at ante aliquet, in hendrerit lectus interdum. Morbi elementum sapien rhoncus pretium maximus. Nulla lectus enim, cursus et elementum sed, sodales vitae eros. Ut ex quam, porta consequat interdum in, faucibus eu velit. Quisque rhoncus ex ac libero varius molestie. Aenean tempor sit amet orci nec iaculis. Cras sit amet nulla libero. Curabitur dignissim, nunc nec laoreet consequat, purus nunc porta lacus, vel efficitur tellus augue in ipsum. Cras in arcu sed metus rutrum iaculis. Nulla non tempor erat. Duis in egestas nunc.\r\n', 25, 450000),
	(2, 'Sweater Champion Red', 'https://i.etsystatic.com/52483035/r/il/6c7e20/6113388476/il_600x600.6113388476_8paa.jpg', 'Nulla eget sem vitae eros pharetra viverra. Mauris consequat ornare feugiat', 'Aenean sit amet gravida nisi. Nam fermentum est felis, quis feugiat nunc fringilla sit amet. Ut in blandit ipsum. Quisque luctus dui at ante aliquet, in hendrerit lectus interdum. Morbi elementum sapien rhoncus pretium maximus. Nulla lectus enim, cursus et elementum sed, sodales vitae eros. Ut ex quam, porta consequat interdum in, faucibus eu velit. Quisque rhoncus ex ac libero varius molestie. Aenean tempor sit amet orci nec iaculis. Cras sit amet nulla libero. Curabitur dignissim, nunc nec laoreet consequat, purus nunc porta lacus, vel efficitur tellus augue in ipsum. Cras in arcu sed metus rutrum iaculis. Nulla non tempor erat. Duis in egestas nunc.\r\n', 50, 500000),
	(2, 'Sweater Champion Black', 'https://i.etsystatic.com/52483035/r/il/6c7e20/6113388476/il_600x600.6113388476_8paa.jpg', 'Nulla eget sem vitae eros pharetra viverra. Mauris consequat ornare feugiat', 'Aenean sit amet gravida nisi. Nam fermentum est felis, quis feugiat nunc fringilla sit amet. Ut in blandit ipsum. Quisque luctus dui at ante aliquet, in hendrerit lectus interdum. Morbi elementum sapien rhoncus pretium maximus. Nulla lectus enim, cursus et elementum sed, sodales vitae eros. Ut ex quam, porta consequat interdum in, faucibus eu velit. Quisque rhoncus ex ac libero varius molestie. Aenean tempor sit amet orci nec iaculis. Cras sit amet nulla libero. Curabitur dignissim, nunc nec laoreet consequat, purus nunc porta lacus, vel efficitur tellus augue in ipsum. Cras in arcu sed metus rutrum iaculis. Nulla non tempor erat. Duis in egestas nunc.\r\n', 70, 480000),

	(3, 'T-shirt Skate', 'https://i.etsystatic.com/52483035/r/il/6c7e20/6113388476/il_600x600.6113388476_8paa.jpg', 'Nulla eget sem vitae eros pharetra viverra. Mauris consequat ornare feugiat', 'Aenean sit amet gravida nisi. Nam fermentum est felis, quis feugiat nunc fringilla sit amet. Ut in blandit ipsum. Quisque luctus dui at ante aliquet, in hendrerit lectus interdum. Morbi elementum sapien rhoncus pretium maximus. Nulla lectus enim, cursus et elementum sed, sodales vitae eros. Ut ex quam, porta consequat interdum in, faucibus eu velit. Quisque rhoncus ex ac libero varius molestie. Aenean tempor sit amet orci nec iaculis. Cras sit amet nulla libero. Curabitur dignissim, nunc nec laoreet consequat, purus nunc porta lacus, vel efficitur tellus augue in ipsum. Cras in arcu sed metus rutrum iaculis. Nulla non tempor erat. Duis in egestas nunc.\r\n', 30, 300000),
	(3, 'Re:values', 'https://i.etsystatic.com/52483035/r/il/6c7e20/6113388476/il_600x600.6113388476_8paa.jpg', 'Nulla eget sem vitae eros pharetra viverra. Mauris consequat ornare feugiat', 'Aenean sit amet gravida nisi. Nam fermentum est felis, quis feugiat nunc fringilla sit amet. Ut in blandit ipsum. Quisque luctus dui at ante aliquet, in hendrerit lectus interdum. Morbi elementum sapien rhoncus pretium maximus. Nulla lectus enim, cursus et elementum sed, sodales vitae eros. Ut ex quam, porta consequat interdum in, faucibus eu velit. Quisque rhoncus ex ac libero varius molestie. Aenean tempor sit amet orci nec iaculis. Cras sit amet nulla libero. Curabitur dignissim, nunc nec laoreet consequat, purus nunc porta lacus, vel efficitur tellus augue in ipsum. Cras in arcu sed metus rutrum iaculis. Nulla non tempor erat. Duis in egestas nunc.\r\n', 100, 320000),
	(3, 'Trust In Our Lord', 'https://i.etsystatic.com/52483035/r/il/6c7e20/6113388476/il_600x600.6113388476_8paa.jpg', 'Nulla eget sem vitae eros pharetra viverra. Mauris consequat ornare feugiat', 'Aenean sit amet gravida nisi. Nam fermentum est felis, quis feugiat nunc fringilla sit amet. Ut in blandit ipsum. Quisque luctus dui at ante aliquet, in hendrerit lectus interdum. Morbi elementum sapien rhoncus pretium maximus. Nulla lectus enim, cursus et elementum sed, sodales vitae eros. Ut ex quam, porta consequat interdum in, faucibus eu velit. Quisque rhoncus ex ac libero varius molestie. Aenean tempor sit amet orci nec iaculis. Cras sit amet nulla libero. Curabitur dignissim, nunc nec laoreet consequat, purus nunc porta lacus, vel efficitur tellus augue in ipsum. Cras in arcu sed metus rutrum iaculis. Nulla non tempor erat. Duis in egestas nunc.\r\n', 90, 380000),

	(4, 'H&M Pants', 'https://i.etsystatic.com/52483035/r/il/6c7e20/6113388476/il_600x600.6113388476_8paa.jpg', 'Nulla eget sem vitae eros pharetra viverra. Mauris consequat ornare feugiat', 'Aenean sit amet gravida nisi. Nam fermentum est felis, quis feugiat nunc fringilla sit amet. Ut in blandit ipsum. Quisque luctus dui at ante aliquet, in hendrerit lectus interdum. Morbi elementum sapien rhoncus pretium maximus. Nulla lectus enim, cursus et elementum sed, sodales vitae eros. Ut ex quam, porta consequat interdum in, faucibus eu velit. Quisque rhoncus ex ac libero varius molestie. Aenean tempor sit amet orci nec iaculis. Cras sit amet nulla libero. Curabitur dignissim, nunc nec laoreet consequat, purus nunc porta lacus, vel efficitur tellus augue in ipsum. Cras in arcu sed metus rutrum iaculis. Nulla non tempor erat. Duis in egestas nunc.\r\n', 40, 550000),
	(4, 'Dark Jeans for Men', 'https://i.etsystatic.com/52483035/r/il/6c7e20/6113388476/il_600x600.6113388476_8paa.jpg', 'Nulla eget sem vitae eros pharetra viverra. Mauris consequat ornare feugiat', 'Aenean sit amet gravida nisi. Nam fermentum est felis, quis feugiat nunc fringilla sit amet. Ut in blandit ipsum. Quisque luctus dui at ante aliquet, in hendrerit lectus interdum. Morbi elementum sapien rhoncus pretium maximus. Nulla lectus enim, cursus et elementum sed, sodales vitae eros. Ut ex quam, porta consequat interdum in, faucibus eu velit. Quisque rhoncus ex ac libero varius molestie. Aenean tempor sit amet orci nec iaculis. Cras sit amet nulla libero. Curabitur dignissim, nunc nec laoreet consequat, purus nunc porta lacus, vel efficitur tellus augue in ipsum. Cras in arcu sed metus rutrum iaculis. Nulla non tempor erat. Duis in egestas nunc.\r\n', 80, 580000),
	(4, 'Brown Jeans', 'https://i.etsystatic.com/52483035/r/il/6c7e20/6113388476/il_600x600.6113388476_8paa.jpg', 'Nulla eget sem vitae eros pharetra viverra. Mauris consequat ornare feugiat', 'Aenean sit amet gravida nisi. Nam fermentum est felis, quis feugiat nunc fringilla sit amet. Ut in blandit ipsum. Quisque luctus dui at ante aliquet, in hendrerit lectus interdum. Morbi elementum sapien rhoncus pretium maximus. Nulla lectus enim, cursus et elementum sed, sodales vitae eros. Ut ex quam, porta consequat interdum in, faucibus eu velit. Quisque rhoncus ex ac libero varius molestie. Aenean tempor sit amet orci nec iaculis. Cras sit amet nulla libero. Curabitur dignissim, nunc nec laoreet consequat, purus nunc porta lacus, vel efficitur tellus augue in ipsum. Cras in arcu sed metus rutrum iaculis. Nulla non tempor erat. Duis in egestas nunc.\r\n', 200, 500000),
	
	(5, 'Jeans New Trendy', 'https://i.etsystatic.com/52483035/r/il/6c7e20/6113388476/il_600x600.6113388476_8paa.jpg', 'Nulla eget sem vitae eros pharetra viverra. Mauris consequat ornare feugiat', 'Aenean sit amet gravida nisi. Nam fermentum est felis, quis feugiat nunc fringilla sit amet. Ut in blandit ipsum. Quisque luctus dui at ante aliquet, in hendrerit lectus interdum. Morbi elementum sapien rhoncus pretium maximus. Nulla lectus enim, cursus et elementum sed, sodales vitae eros. Ut ex quam, porta consequat interdum in, faucibus eu velit. Quisque rhoncus ex ac libero varius molestie. Aenean tempor sit amet orci nec iaculis. Cras sit amet nulla libero. Curabitur dignissim, nunc nec laoreet consequat, purus nunc porta lacus, vel efficitur tellus augue in ipsum. Cras in arcu sed metus rutrum iaculis. Nulla non tempor erat. Duis in egestas nunc.\r\n', 30, 480000),
	(5, 'Jeans Star Fire', 'https://i.etsystatic.com/52483035/r/il/6c7e20/6113388476/il_600x600.6113388476_8paa.jpg', 'Nulla eget sem vitae eros pharetra viverra. Mauris consequat ornare feugiat', 'Aenean sit amet gravida nisi. Nam fermentum est felis, quis feugiat nunc fringilla sit amet. Ut in blandit ipsum. Quisque luctus dui at ante aliquet, in hendrerit lectus interdum. Morbi elementum sapien rhoncus pretium maximus. Nulla lectus enim, cursus et elementum sed, sodales vitae eros. Ut ex quam, porta consequat interdum in, faucibus eu velit. Quisque rhoncus ex ac libero varius molestie. Aenean tempor sit amet orci nec iaculis. Cras sit amet nulla libero. Curabitur dignissim, nunc nec laoreet consequat, purus nunc porta lacus, vel efficitur tellus augue in ipsum. Cras in arcu sed metus rutrum iaculis. Nulla non tempor erat. Duis in egestas nunc.\r\n', 150, 580000),
	(5, 'Jeans 2023SS Girls', 'https://i.etsystatic.com/52483035/r/il/6c7e20/6113388476/il_600x600.6113388476_8paa.jpg', 'Nulla eget sem vitae eros pharetra viverra. Mauris consequat ornare feugiat', 'Aenean sit amet gravida nisi. Nam fermentum est felis, quis feugiat nunc fringilla sit amet. Ut in blandit ipsum. Quisque luctus dui at ante aliquet, in hendrerit lectus interdum. Morbi elementum sapien rhoncus pretium maximus. Nulla lectus enim, cursus et elementum sed, sodales vitae eros. Ut ex quam, porta consequat interdum in, faucibus eu velit. Quisque rhoncus ex ac libero varius molestie. Aenean tempor sit amet orci nec iaculis. Cras sit amet nulla libero. Curabitur dignissim, nunc nec laoreet consequat, purus nunc porta lacus, vel efficitur tellus augue in ipsum. Cras in arcu sed metus rutrum iaculis. Nulla non tempor erat. Duis in egestas nunc.\r\n', 85, 600000),
	
	(6, 'Heaven Sent Cropped top', 'https://i.etsystatic.com/52483035/r/il/6c7e20/6113388476/il_600x600.6113388476_8paa.jpg', 'Nulla eget sem vitae eros pharetra viverra. Mauris consequat ornare feugiat', 'Aenean sit amet gravida nisi. Nam fermentum est felis, quis feugiat nunc fringilla sit amet. Ut in blandit ipsum. Quisque luctus dui at ante aliquet, in hendrerit lectus interdum. Morbi elementum sapien rhoncus pretium maximus. Nulla lectus enim, cursus et elementum sed, sodales vitae eros. Ut ex quam, porta consequat interdum in, faucibus eu velit. Quisque rhoncus ex ac libero varius molestie. Aenean tempor sit amet orci nec iaculis. Cras sit amet nulla libero. Curabitur dignissim, nunc nec laoreet consequat, purus nunc porta lacus, vel efficitur tellus augue in ipsum. Cras in arcu sed metus rutrum iaculis. Nulla non tempor erat. Duis in egestas nunc.\r\n', 99, 150000),
	(6, 'Blue Cropped top', 'https://i.etsystatic.com/52483035/r/il/6c7e20/6113388476/il_600x600.6113388476_8paa.jpg', 'Nulla eget sem vitae eros pharetra viverra. Mauris consequat ornare feugiat', 'Aenean sit amet gravida nisi. Nam fermentum est felis, quis feugiat nunc fringilla sit amet. Ut in blandit ipsum. Quisque luctus dui at ante aliquet, in hendrerit lectus interdum. Morbi elementum sapien rhoncus pretium maximus. Nulla lectus enim, cursus et elementum sed, sodales vitae eros. Ut ex quam, porta consequat interdum in, faucibus eu velit. Quisque rhoncus ex ac libero varius molestie. Aenean tempor sit amet orci nec iaculis. Cras sit amet nulla libero. Curabitur dignissim, nunc nec laoreet consequat, purus nunc porta lacus, vel efficitur tellus augue in ipsum. Cras in arcu sed metus rutrum iaculis. Nulla non tempor erat. Duis in egestas nunc.\r\n', 30, 220000),
	(6, 'Brown Cropped top', 'https://i.etsystatic.com/52483035/r/il/6c7e20/6113388476/il_600x600.6113388476_8paa.jpg', 'Nulla eget sem vitae eros pharetra viverra. Mauris consequat ornare feugiat', 'Aenean sit amet gravida nisi. Nam fermentum est felis, quis feugiat nunc fringilla sit amet. Ut in blandit ipsum. Quisque luctus dui at ante aliquet, in hendrerit lectus interdum. Morbi elementum sapien rhoncus pretium maximus. Nulla lectus enim, cursus et elementum sed, sodales vitae eros. Ut ex quam, porta consequat interdum in, faucibus eu velit. Quisque rhoncus ex ac libero varius molestie. Aenean tempor sit amet orci nec iaculis. Cras sit amet nulla libero. Curabitur dignissim, nunc nec laoreet consequat, purus nunc porta lacus, vel efficitur tellus augue in ipsum. Cras in arcu sed metus rutrum iaculis. Nulla non tempor erat. Duis in egestas nunc.\r\n', 20, 180000)
go

insert into [ProductImages] values
	(1,'/images/product/1/White-Slyteam-Jacket-Front-1000x1250.jpg'),
	(2, '/images/product/2/Black-Slyteam-Jacket-Back-1000x1250.jpg'),
	(3, '/images/product/3/doncare-PROM-COLLAGE-JACKET-01.jpg'),
	(4, '/images/product/4/EE1A0D20-A1E4-4A8D-A532-840BB9D6DFF0.png'), 
	(5, '/images/product/5/83FD173B-87AC-4087-92C1-8E8F0AF0242A.png'), 
	(6, '/images/product/6/3ce9e4f9462ca1a80f9bae7462d2a591.jpg'), 
	(7, '/images/product/7/161682917869c354f27b7fc10c9eafec.jpg'), 
	(8, '/images/product/8/4fdbae083275462f9a67224b74ff65ff.jpg'), 
	(9, '/images/product/9/Layer-1.png'), 
	(10, '/images/product/10/hmgoepprod.jpg'), 
	(11, '/images/product/11/0052041802_1_1_1.jpg'), 
	(12, '/images/product/12/3349484c7665963da157549482999e2e.jpg'), 
	(13, '/images/product/13/2cb8fba5b7af8b2f937f46dc732738b6.jpg'), 
	(14, '/images/product/14/619f250fa706ba5d84534515c4d02659.jpg'), 
	(15, '/images/product/15/c8d59bbc2249a50b8db92e2c2cbc137f.jpg'), 
	(16, '/images/product/16/d45d5314e64cb425f9489b1300bfa472.jpg'), 
	(17, '/images/product/17/a7c2edd53365a95455113e9745f133aa.jpg'), 
	(18, '/images/product/18/061148dfa1fb2ba3b777de1c5140859e.jpg')
go




insert into [Sizes] values
	('1S',1,'S',10,200000),
	('1L',1,'L',10,300000),
	('1M',1,'M',10,400000),
	('2S',2,'S',10,200000),
	('3S',3,'S',10,200000),
	('4S',4,'S',10,200000),
	('5S',5,'S',10,200000)
go 







